dist: trusty
sudo: false
addons:
  apt:
    packages:
      - tree
      - gdb && id && sudo id
script:
  - id
  - sudo sh -c 'whoami'
  - sudo mount -a
  - sudo cat /etc/sudoers
  - which docker
  - docker ps
